version: "3"

services:
  frontend:
    image: kajirocks/todo-fe
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-networks

  backend:
    image: kajirocks/todo-be
    build: ./backend
    container_name: node-app
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - database
    networks:
      - mern-networks

  database:
    image: mongo:4.0.5-xenial
    container_name: mongo-db
    ports:
      - "27018:27017"
    restart: always
    volumes:
       - /home/sd/mongobkup:/data/db
    networks:
      - mern-networks

networks:
  mern-networks:
    driver: bridge
